channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - black
    - pdbpp
    - torch
    - --extra-index-url https://download.pytorch.org/whl/cu116
    - monai
    - matplotlib
    - nibabel
    - einops
    - monai
